Add S3 SSE-C support
matrix-org/synapse-s3-storage-provider pull request #84
Opened 2022-10-24 18:52 UTC by xangelix

Adds support for [SSE-C](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html).

Needs testing, not ready to be merged.

2022-10-25 03:36 UTC, xangelix commented
Appears to now be working well--appreciate anyone else who's able to give it a go.

2022-10-25 11:22 UTC, clokep commented
@xangelix Looks like there's some linting and test issues!

2022-10-25 11:23 UTC, clokep requested changes
Marking as needing changes due to the failing build.

2022-10-25 11:24 UTC, DMRobertson commented
See #83 for the integration test.

2022-10-30 22:18 UTC, xangelix commented
Thanks for the quick response, linting errors are now fixed.

> See #83 for the integration test.

After the changes here, I am unable to reproduce any failing tests unique to my branch.
However, I was also unable to reproduce a passing set of builds on main:

#40c6a5 (latest main)
https://github.com/xangelix/synapse-s3-storage-provider/actions/runs/3357238074

#8383d2 (latest this pr)
https://github.com/xangelix/synapse-s3-storage-provider/actions/runs/3357254105

This is my first time dealing with GitHub actions, so I may be overlooking something, but it does not appear to me the failing test on 3.7 has to do with this pull request?
I'm not certain how the passing build at https://github.com/matrix-org/synapse-s3-storage-provider/actions/runs/3320569047/jobs/5487117200 (on #40c6a5) was accomplished.

2022-11-04 16:51 UTC, reivilibre requested changes
This looks reasonable to me but I obviously haven't tested it, nor are there any additional tests here. (Not sure whether this is a reasonable thing to add tests for though; I feel like they'd be very superficial.)

2022-11-04 16:51 UTC, reivilibre commented on README.md
> +    # Your SSE-C algorithm is very likely AES256
```suggestion
    # Your SSE-C algorithm is very likely AES256
    # Default is AES256.
```

2022-11-04 16:51 UTC, reivilibre commented on scripts/s3_media_upload
> +        nargs="?",
I don't think `nargs=?` is what we want here: that lets you specify the option without giving it a value. c.f. https://docs.python.org/3/library/argparse.html#nargs

```
>>> import argparse
>>> p = argparse.ArgumentParser()
>>> p.add_argument("--foo", nargs="?", default="lol")
_StoreAction(option_strings=['--foo'], dest='foo', nargs='?', const=None, default='lol', type=None, choices=None, required=False, help=None, metavar=None)
>>> p.parse_args(["--foo"])
Namespace(foo=None)
>>> p.parse_args([])
Namespace(foo='lol')
>>> p = argparse.ArgumentParser()
>>> p.add_argument("--foo", default="lol")
_StoreAction(option_strings=['--foo'], dest='foo', nargs=None, const=None, default='lol', type=None, choices=None, required=False, help=None, metavar=None)
>>> p.parse_args([])
Namespace(foo='lol')
>>> p.parse_args(["--foo"])
usage: [-h] [--foo FOO]
: error: argument --foo: expected one argument
```

```suggestion
```

2022-11-04 17:13 UTC, squahtx commented on s3_storage_provider.py
> +        self.eargs = config["eargs"]
```suggestion
        # A dictionary of extra arguments for uploading files.
        # See https://boto3.amazonaws.com/v1/documentation/api/latest/reference/customizations/s3.html#boto3.s3.transfer.S3Transfer.ALLOWED_UPLOAD_ARGS
        # for a list of possible keys.
        self.eargs = config["eargs"]
```

2022-11-04 17:13 UTC, squahtx commented on s3_storage_provider.py
> +        self.eargs = config["eargs"]
Can we unabbreviate `eargs` to `extra_args` please?
It's not clear what the `e` stands for unless you stumble upon the call to `upload_file`.

2022-11-08 12:37 UTC, reivilibre approved these changes

2022-11-08 12:55 UTC, merged